modLoader="javafml"
loaderVersion="[4,)"
license="moritz_htk Software License Agreement (mSLA)"
issueTrackerURL="https://github.com/moritz-htk/idle-boost/issues"

[[mods]]
    modId="idle_boost"
    version="${version}"
    displayName="Idle Boost"
    updateJSONURL="https://api.modrinth.com/updates/idle-boost/forge_updates.json?neoforge=only"
    displayURL="https://sites.google.com/view/moritz-htk/mods/idle-boost"
    logoFile="assets/idle_boost/icon.png"
    authors="moritz_htk"
    description='''This mod optimizes performance when Minecraft is running in the background.'''

[[dependencies.idle_boost]]
    modId="neoforge"
    type="required"
    versionRange="[21.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.idle_boost]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,)"
    ordering="NONE"
    side="BOTH"